Deployable bash script clean up

diff --git a/deployable-scripts/src/main/dist/bin/kill b/deployable-scripts/src/main/dist/bin/kill
--- a/deployable-scripts/src/main/dist/bin/kill
+++ b/deployable-scripts/src/main/dist/bin/kill
@@ -5,21 +5,20 @@ SERVICE_NAME=$(basename $APP_ROOT);
 
 IS_RUNNING=`ps -ef | grep "\-DserviceName="${SERVICE_NAME} | grep -v "grep " | wc -l`
 if [ $IS_RUNNING -eq 0 ]; then
-    echo "Service "${SERVICE_NAME}" isn't running!"
-    exit 0;
+    echo "Service "${SERVICE_NAME}" is not running"
+    exit 1
 fi
 
 echo "Stopping "${SERVICE_NAME}
 PID=`ps -ef | grep "\-DserviceName="${SERVICE_NAME} | grep -v "grep " | awk '{ print $2 }'`
 echo "killing pid "$PID
 kill -9 $PID
-# wait for process to be killed
 sleep 2
 
 IS_STILL_RUNNING=`ps -ef | grep "\-DserviceName="${SERVICE_NAME} | grep -v "grep " | wc -l`
 if [ $IS_STILL_RUNNING -ne 0 ]; then
-    echo "FAILED to stop "${SERVICE_NAME}
-    exit 1;
+    echo "Failed to stop "${SERVICE_NAME}
+    exit 1
 fi
-echo "SUCCESS Stopped "${SERVICE_NAME}
-exit 0;
+
+echo "Successfully stopped "${SERVICE_NAME}
